general:
  device: "mps"
  screen_descriptor:
    include_text: true
    text_prefix: "Text element:"
    icon_prefix: "Icon:"

template_matching:
  enabled: true
  database_path: "data/icon_templates.csv"
  threshold: 0.8

icon_detection:
  default: "template"
  available_detectors:
    - template
  yolo:
    model_path: "src/compass/tools/screen_parser/data/icon_detect_v1_5/model_v1_5.pt"
    device: "${general.device}"
    conf_threshold: 0.4
    iou_threshold: 0.1
  template:
    database_path: "data/icon_templates.csv"
    threshold: 0.8

text_detection:
  default: "google"
  available_detectors:
    - google
  google:
    region: "us-west1"

captioning:
  enabled: true
  default: "claude"
  available_captioners:
    - claude
  claude:
    model: "claude-3-5-sonnet-20241022"
    batch_size: 1
    run_claude: false
    icon_matcher:
      database_path: "src/compass/tools/screen_parser/data/icon_database.pkl"
      similarity_threshold: 0.95 